name: dmg版本打包

on:
  workflow_dispatch:  # 手动触发
#  push:
#    tags:
#      - '*'  # 监听所有标签推送事件

jobs:
  build:
    runs-on: macos-13  # 使用最新版本的 macOS

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Java 23 (Oracle OpenJDK 23.0.1 - aarch64)
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '23.0.1'
          architecture: 'x64'  # 指定 aarch64 架构

      # 3. 验证 Java 版本
      - name: Verify Java version
        run: java -version

      # 4. 赋予 Gradle 执行权限（如果需要）
      - name: Make Gradle executable
        run: chmod +x gradlew

      # 5. 运行 Gradle 任务
      - name: Run Gradle packageReleaseDistributionForCurrentOS
        run: ./gradlew packageReleaseDistributionForCurrentOS

      # 6. 上传到artifact中
      - name: Upload logs to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-package-release  # Artifact 的名称
          path: composeApp\build\compose\logs\packageRelease*  # 要上传的目录
