name: 上传和下载测试

on:
  workflow_dispatch: # 手动触发 (变量引用的时候使用 ${{ github.event.inputs.tag_name }})
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: windows-latest  # 使用最新版本的 windows
    steps:
      - name: Create folder and files
        run: |
          mkdir -p D:\a\ComposeApp-projects\ComposeApp-projects\composeApp\build\customOutputDir\main-release
          echo "This is file 1" > D:\a\ComposeApp-projects\ComposeApp-projects\composeApp\build\customOutputDir\main-release\file1.txt
          echo "This is file 2" > D:\a\ComposeApp-projects\ComposeApp-projects\composeApp\build\customOutputDir\main-release\file2.txt

      # 7. 上传打包出来的文件到 Artifacts
      - name: Upload Releases to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-release  # Artifact 的名称
          path: |
            D:\a\ComposeApp-projects\ComposeApp-projects\composeApp\build\customOutputDir\main-release\*

  # Job 3: 创建 Release 并上传 .dmg 和 .exe 文件
  create-release:
    runs-on: ubuntu-latest  # 使用轻量级的 Ubuntu 环境
    needs: [build]  # 依赖 build-mac 和 build-windows job
    permissions:
      contents: write  # 允许写入仓库内容

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-release
          path: ./artifacts

      - name: List extracted files
        run: |
          ls -R ./artifacts