name: windows版本打包

on:
  push:
    branches:
      - main  # 你可以指定特定的分支，例如 main 或 master

jobs:
  build:
    runs-on: windows-latest  # 使用最新版本的 windows

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Java 23 (Oracle OpenJDK 23.0.1 - aarch64)
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23.0.1'
          architecture: 'x64'  # 指定 aarch64 架构

      # 3. 验证 Java 版本
      - name: Verify Java version
        run: java -version

      # 4. 赋予 Gradle 执行权限（如果需要）
      - name: Make Gradle executable
        run: chmod +x gradlew

      # 5. 运行 Gradle 任务
      - name: Run Gradle packageReleaseDistributionForCurrentOS
        run: ./gradlew packageReleaseDistributionForCurrentOS

      # 6. 上传日志文件到 Artifacts
      - name: Upload logs to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package-release-logs  # Artifact 的名称
          path: D:\a\ComposeApp-projects\ComposeApp-projects\composeApp\build\compose\logs\packageReleaseExe  # 要上传的目录