name: Send Random String on Push

on:
  workflow_dispatch: # 手动触发 (变量引用的时候使用 ${{ github.event.inputs.tag_name }})
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use environment variables
        run: |
          echo "Using EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}"
          echo "Using EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}"

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "new Tag on Push"
          body: "A push event occurred. New tag is ${{ github.event.inputs.tag_name }}"
          to: 414078812@qq.com
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/plain